spring.application.name=backend

spring.datasource.url= jdbc:mysql://localhost:3306/onboarding_db
spring.datasource.username=root
spring.datasource.password=HeitorMYSQL2005.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true